//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseChessControl.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChineseChessControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 炮 的本地化字符串。
        /// </summary>
        internal static string Cannon {
            get {
                return ResourceManager.GetString("Cannon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 楚河 的本地化字符串。
        /// </summary>
        internal static string ChuHe {
            get {
                return ResourceManager.GetString("ChuHe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 象 的本地化字符串。
        /// </summary>
        internal static string Elephant {
            get {
                return ResourceManager.GetString("Elephant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将 的本地化字符串。
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 士 的本地化字符串。
        /// </summary>
        internal static string Guard {
            get {
                return ResourceManager.GetString("Guard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 汉界 的本地化字符串。
        /// </summary>
        internal static string HanJie {
            get {
                return ResourceManager.GetString("HanJie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帥 的本地化字符串。
        /// </summary>
        internal static string King {
            get {
                return ResourceManager.GetString("King", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 馬 的本地化字符串。
        /// </summary>
        internal static string Knight {
            get {
                return ResourceManager.GetString("Knight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仕 的本地化字符串。
        /// </summary>
        internal static string Mandarin {
            get {
                return ResourceManager.GetString("Mandarin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相 的本地化字符串。
        /// </summary>
        internal static string Minister {
            get {
                return ResourceManager.GetString("Minister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卒 的本地化字符串。
        /// </summary>
        internal static string Pawn {
            get {
                return ResourceManager.GetString("Pawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 車 的本地化字符串。
        /// </summary>
        internal static string Rook {
            get {
                return ResourceManager.GetString("Rook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 兵 的本地化字符串。
        /// </summary>
        internal static string Soldier {
            get {
                return ResourceManager.GetString("Soldier", resourceCulture);
            }
        }
    }
}
